### ISSUE TITLE
Error: Error detecting input file format. First line seems to be blank.

### ISSUE THREAD

**Issue by qussai96** [gatech-genemark/ProtHint#45] opened 2022-08-25 20:51 UTC
Hi Tomas,
I am trying to run prothint with seeds generated by braker.
I am getting the following error:

```
#CPU threads: 16
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory:
#Target sequences to report alignments for: 25
Opening the database...  [0.109s]
Database: diamond_db.dmnd (type: Diamond database, sequences: 24502072, letters: 9300670097)
Block size = 2000000000
Opening the input file...  [0s]
Error: Error detecting input file format. First line seems to be blank.
[Thu Aug 25 20:19:17 2022] error: ProtHint exited due to an error in command: /home/qabbas/Plants/Tools/ProtHint-2.6.0/bin/../dependencies/diamond blastp --query ../seed_proteins.faa --db diamond_db --outfmt 6 qseqid sseqid --out diamond.out --max-target-seqs 25 --max-hsps 1 --threads 16 --evalue 0.001
```
I tried to change diamond version in dependencies folder with the latest version but this didn't help, and I am still getting the same error.

The command I am running is:
`prothint.py --threads=16 --workdir=ProtHint_dir --geneSeeds=./braker_seeds/augustus.hints.gtf GCF_000001735.4_TAIR10.1_genomic.fna.masked orthodb_without_AT.fasta `

Thanks,

**Comment by qussai96** [comment] 2022-08-26 13:28
it seems like the problem is with the script "proteins_from_gtf.pl" as the seed_proteins.faa file is empty.

**Comment by tomasbruna** [comment] 2022-08-27 00:49
ProtHint should still work with the BRAKER seeds (anything other than the CDS lines are ignored).

Can you share your input files (by email to bruna.tomas@gmail.com if you don't want to share here)? I will try to run ProtHint myself and reproduce this error.

Best,
Tomas

**Comment by qussai96** [comment] 2022-08-27 10:18
Thank you @tomasbruna for your reply.
I have sent the input files by email.

best,

**Comment by tomasbruna** [comment] 2022-08-28 21:29
Hi Qussai,

thanks for sending the files. The error is caused by a mismatch in contig names between `augustus.hints.gtf` and `GCF_000001735.4_TAIR10.1_genomic.fna`. One of them has spaces between words:

    NC_003070.9 Arabidopsis thaliana chromosome 1 sequence

and the other one uses underscores:

    NC_003070.9_Arabidopsis_thaliana_chromosome_1_sequence

It is possible that the underscores were automatically added over the course of a ProtHint run. In any case, the error can be fixed by renaming the contigs to make sure they are matching.

Best,
Tomas

**Comment by qussai96** [comment] 2022-08-28 22:21
Thank you, Tomas!
I renamed the contigs and everything is working perfectly now.

cheers,
Qussai

**Closed** 2022-08-29 01:51 UTC
